import streamlit as st

from utils.api_manager import APIManager
from utils.language_manager import LanguageManager
from utils.logging import configure_logger
from utils.logo import generate_logo

logger = configure_logger(__file__)

st.set_page_config(page_title="chat-o-sophy", page_icon="💭", layout="wide")


def main():
    logger.info("Running home")

    st.session_state.setdefault("language_manager", LanguageManager())
    st.session_state.setdefault("api_manager", APIManager())

    with st.sidebar:
        st.session_state.language_manager.display()
        st.sidebar.divider()
        st.session_state.api_manager.display()

    col1, col2 = st.columns(spec=[0.7, 0.3], gap="large")
    with col1:
        st.title("💭 chat-o-sophy", anchor=False)
        st.write(
            "[![source code](https://img.shields.io/badge/view_source_code-gray?logo=github)](https://github.com/daltunay/chat-o-sophy)"
        )
        st.header("Chat with your favorite philosophers!", divider="gray", anchor=False)
        st.markdown(
            """
        _chat-o-sophy_ lets you engage in enlightening conversations with famous philosophers.
        
        Choose from two modes:
        - **[single mode](single_mode)**: have a one-on-one conversation with a chosen philosopher and explore their unique perspectives.
        - **[multi mode](multi_mode)**: ask a question and get answers from multiple philosophers, gaining a well-rounded perspective.
        """
        )

    st.header("How it works", anchor=False, divider="gray")
    _col1, _col2 = st.columns(2)
    with _col1:
        st.subheader("Single mode", anchor=False)
        st.markdown(
            """
            1. **Choose a philosopher**: Select from renowned philosophers.
            2. **Have them welcome you**: Read about their topics of interest.
            3. **Chat with them**: Start a conversation with anything you want.
            """
        )
    with _col2:
        st.subheader("Multi mode", anchor=False)
        st.markdown(
            """
            1. **Choose several philosophers**: Select from renowned philosophers.
            2. **Ask a question**: Ask about anything you want to learn about.
            3. **Receive responses**: Enjoy thought-provoking answers from them.
            """
        )

    st.header("About", anchor=False, divider="gray")
    st.markdown(
        """
        _chat-o-sophy_ harnesses the power of Large Language Models (LLM) to allow you to chat with your favorite philosophers.  
        Using the OpenAI API, this app employs GPT-3.5 via the `langchain` library, as well as DALL·E 2 for the logo generation.
        """
    )

    st.divider()

    st.columns([1, 0.5, 1])[1].markdown(
        "_Made by Daniel Altunay_"
        "[![LinkedIn](https://img.icons8.com/?id=13930&format=png)](https://linkedin.com/in/daltunay)"
        "[![GitHub](https://img.icons8.com/?id=AZOZNnY73haj&format=png)](https://github.com/daltunay)"
    )

    with col2:
        logo = generate_logo()
        st.image(logo, use_column_width=True, caption="generated by DALL·E 2")
        st.button(
            label="Generate new logo",
            use_container_width=True,
            on_click=generate_logo.clear,
        )
    

if __name__ == "__main__":
    main()
