gpt-3.5-turbo:
  model_provider: openai
  model_owner: null
  model_version: null
  experimental_flag: false

mistral-7b-instruct-v0.1:
  model_provider: replicate
  model_owner: mistralai
  model_version: 83b6a56e7c828e667f21fd596c338fd4f0039b46bcfa18d973e8e70e455fda70
  experimental_flag: true

llama-2-7b-chat:
  model_provider: replicate
  model_owner: meta
  model_version: 13c3cdee13ee059ab779f0291d29054dab00a47dad8261375654de5540165fb0
  experimental_flag: true

dolly-v2-12b:
  model_provider: replicate
  model_owner: replicate
  model_version: ef0e1aefc61f8e096ebe4db6b2bacc297daf2ef6899f0f7e001ec445893500e5
  experimental_flag: true